dist: xenial

language: python

cache: pip

branches:
  only:
    - master
    - dev
    - build
    - build-test

# python versions to test
python:
  - "3.7"

# command to install dependencies
install:
  - python -m pip install -r requirements.txt

# command to run tests
script:
  - python3 -m pytest -m "not manual"
