language: python

branches:
  only:
    - master
    - dev
    - loganalyser

python:
  - "3.7"

# command to install dependencies
install:
  - python setup.py install

# command to run tests
script:
  - python3 -m pytest